# **Array Oriented Programming**

##  Universal Functions:


In [2]:
import numpy as np

In [11]:
arr = np.arange(10)
#sqrt
print(np.sqrt(arr))
#exp
print(np.exp(arr))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


### How does `np.maximum` function ?
- If a[i] > b[i], then a[i] is placed in the result.
- If a[i] <= b[i], then b[i] is placed in the result.


In [13]:
x = np.random.standard_normal(10)
y = np.random.standard_normal(10)
print(f'{x}\n{y}')
print(f'max : {np.maximum(x,y)}')
print(f'min : {np.minimum(x,y)}')

[ 0.25831309  1.79738034 -0.47017928 -0.47490384  1.34270841  0.50422142
 -0.13720267  0.76689801  1.51306096 -0.0708849 ]
[-3.60911095 -0.34041757 -1.23490892 -1.21199021  1.02297681  0.02093087
  0.04373671 -0.93388082  0.56279285  0.88556837]
max : [ 0.25831309  1.79738034 -0.47017928 -0.47490384  1.34270841  0.50422142
  0.04373671  0.76689801  1.51306096  0.88556837]
min : [-3.60911095 -0.34041757 -1.23490892 -1.21199021  1.02297681  0.02093087
 -0.13720267 -0.93388082  0.56279285 -0.0708849 ]


| Function          | Description                                                                                                           |
|-------------------|-----------------------------------------------------------------------------------------------------------------------|
| `abs`, `fabs`     | Compute the absolute value element-wise for integer, floating-point, or complex values                                |
| `sqrt`            | Compute the square root of each element (equivalent to `arr ** 0.5`)                                                  |
| `square`          | Compute the square of each element (equivalent to `arr ** 2`)                                                         |
| `exp`             | Compute the exponent \(e^x\) of each element                                                                          |
| `log`, `log10`, `log2`, `log1p` | Natural logarithm (base e), log base 10, log base 2, and log(1 + x), respectively                        |
| `sign`            | Compute the sign of each element: 1 (positive), 0 (zero), or -1 (negative)                                            |
| `ceil`            | Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)                 |
| `floor`           | Compute the floor of each element (i.e., the largest integer less than or equal to each element)                      |
| `rint`            | Round elements to the nearest integer, preserving the dtype                                                           |
| `modf`            | Return fractional and integral parts of an array as separate arrays                                                   |
| `isnan`           | Return Boolean array indicating whether each value is NaN (Not a Number)                                              |
| `isfinite`, `isinf` | Return Boolean array indicating whether each element is finite (non-inf, non-NaN) or infinite, respectively         |
| `cos`, `cosh`, `sin`, `sinh`, `tan`, `tanh` | Regular and hyperbolic trigonometric functions                                              |
| `arccos`, `arccosh`, `arcsin`, `arcsinh`, `arctan`, `arctanh` | Inverse trigonometric functions                                          |
| `logical_not`     | Compute truth value of `not x` element-wise (equivalent to `~arr`)                                                   |

### fractional and integral parts of a floating-point array

In [25]:
arr = np.random.standard_normal(5)*5
# The purpose of multiplying by 5 is to generate random values from a normal distribution 
# that is still centered around 0 but with a wider spread (larger standard deviation).
remainder, whole_part = np.modf(arr)
print(arr)
print(f'remainder: {remainder}')
print(f'integer : {whole_part}')

[ 3.76240481 -1.09181543 -1.04429931  7.17590079 -1.23341276]
remainder: [ 0.76240481 -0.09181543 -0.04429931  0.17590079 -0.23341276]
integer : [ 3. -1. -1.  7. -1.]


### Conditional Logic as Array Operations
Suppose we wanted to take a value from xarr whenever the corresponding value in
cond is True, and otherwise take the value from yarr.


In [35]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
yarr = np.array([2.1,2.2,2.3,2.4,2.5])
cond = np.array([True,False,True,True,False])
cond2 = np.array([1,0,1,1,0])
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [49]:
arr = np.random.randint(low=-5, high=6, size=(4, 4))
print(arr)
print(arr > 0)
# setting every value to a positive number
np.where(arr > 0,arr,-arr) 

[[ 2  4  2  1]
 [-1 -3 -5 -3]
 [-2  0 -5 -4]
 [ 0 -3 -5 -3]]
[[ True  True  True  True]
 [False False False False]
 [False False False False]
 [False False False False]]


array([[2, 4, 2, 1],
       [1, 3, 5, 3],
       [2, 0, 5, 4],
       [0, 3, 5, 3]])

### Mathematical and Statistical Methods

In [59]:
arr = np.random.randint(low=-100,high=100, size =(5,5))
print(arr)
print(f'abs :\n {np.abs(arr)}')
print(f'sum : {np.sum(arr)}')
print(f'mean : {np.mean(arr)}')
print(f'average : {np.average(arr)}')

[[-84 -82 -79 -65  85]
 [-69 -70  38  59  88]
 [-12 -44 -81 -66 -23]
 [-35  24 -71  21  95]
 [ 91 -60 -19  58 -34]]
abs :
 [[84 82 79 65 85]
 [69 70 38 59 88]
 [12 44 81 66 23]
 [35 24 71 21 95]
 [91 60 19 58 34]]
sum : -335
mean : -13.4
average : -13.4


In [60]:
arr = np.random.randint(low=-100,high=100, size =(5,5))
print(arr)
# Here, arr.mean(axis=1) means “compute mean across the columns,” where arr.sum(axis=0) means “compute sum down the rows.”
arr.sum(axis=0)

[[ 49 -17  22 -15   2]
 [-35 -30 -88  55 -28]
 [ 66  28   4  47   1]
 [  5  70  48  29  29]
 [-44 -13  69 -68 -50]]


array([ 41,  38,  55,  48, -46])

- Cumulative sums, or running totals, are used to display the total sum of data as it grows with time

In [61]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28])

For each column, compute the cumulative sum of the elements. This means that for each element in a column, you add it to the sum of the elements above it in the same column.

In [64]:
arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(f'computes the cumulative sum along the rows ( through the columns ) :\n {arr.cumsum(axis=0)}')
print(f'computes the cumulative sum along the columns ( through the rows ) :\n {arr.cumsum(axis=1)}')

computes the cumulative sum along the rows ( through the columns ) :
 [[ 1  2  3]
 [ 5  7  9]
 [12 15 18]]
computes the cumulative sum along the columns ( through the rows ) :
 [[ 1  3  6]
 [ 4  9 15]
 [ 7 15 24]]


| Method       | Description                                                                                 |
|--------------|---------------------------------------------------------------------------------------------|
| `sum`        | Sum of all the elements in the array or along an axis; zero-length arrays have sum 0        |
| `mean`       | Arithmetic mean; invalid (returns NaN) on zero-length arrays                                |
| `std`, `var` | Standard deviation and variance, respectively                                                |
| `min`, `max` | Minimum and maximum                                                                          |
| `argmin`, `argmax` | Indices of minimum and maximum elements, respectively                                  |
| `cumsum`     | Cumulative sum of elements starting from 0                                                   |
| `cumprod`    | Cumulative product of elements starting from 1                                               |


sum is often used as a means of counting True values in a Boolean array:

In [76]:
arr = np.random.randint(low=0,high=2,size=(4,4))
arr = arr.astype(bool)
print(arr)
print(f'number of trues : {arr.sum()}')
# if any value is True
print(arr.any())
# if all the values are True
print(arr.all())

[[False  True False  True]
 [False  True  True False]
 [False  True  True  True]
 [False False  True False]]
number of trues : 8
True
False


In [75]:
arr = np.random.standard_normal(20)
print(arr)
print(f'number of trues : {(arr>0).sum()}')

[ 0.75549789  0.99123452 -1.06999637 -0.4612214   1.94447775 -0.40661171
  0.25680135  0.45227684  1.33493103  1.07025406 -0.4347959  -0.05403803
  0.46523537 -0.8971996   1.08196901 -0.88867604  0.86815444 -1.27857436
  0.06306072 -0.33753665]
number of trues : 11
