In [1]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_00))

* NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.


In [9]:
%timeit my_arr2 = my_arr * 2

1.24 ms ± 29.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
%timeit my_list2 = [x * 2 for x in my_list]

3.47 ms ± 92.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.

In [11]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
data * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [22]:
data.ndim

2

In [20]:
data.shape

(3, 3)

In [21]:
data.dtype

dtype('int32')

converting lists into arrays :

In [24]:
lst1 = [[1,1,1,1],[1,1,1,1]]
arr1 = np.array(lst1)
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.zeros([4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### important NumPy array creation functions
| Function         | Description                                                                                                                                          |
|------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| `array`          | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default. |
| `asarray`        | Convert input to ndarray, but do not copy if the input is already an ndarray.                                                                        |
| `arange`         | Like the built-in `range` but returns an ndarray instead of a list.                                                                                  |
| `ones`           | Produce an array of all 1s with the given shape and data type.                                                                                       |
| `ones_like`      | Takes another array and produces a ones array of the same shape and data type.                                                                       |
| `zeros`          | Like `ones` but producing arrays of 0s instead.                                                                                                      |
| `zeros_like`     | Takes another array and produces a zeros array of the same shape and data type.                                                                      |
| `empty`          | Create new arrays by allocating new memory, but do not populate with any values like `ones` and `zeros`.                                             |
| `empty_like`     | Takes another array and produces an empty array of the same shape and data type.                                                                     |
| `full`           | Produce an array of the given shape and data type with all values set to the indicated “fill value.”                                                 |
| `full_like`      | Takes another array and produces a filled array of the same shape and data type.                                                                     |
| `eye`, `identity`| Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere).                                                                         |


### Numpy Datatypes :
| Type          | Type Code  | Description                                                                                               |
|---------------|------------|-----------------------------------------------------------------------------------------------------------|
| `int8`, `uint8`   | `i1`, `u1`   | Signed and unsigned 8-bit (1 byte) integer types                                                          |
| `int16`, `uint16` | `i2`, `u2`   | Signed and unsigned 16-bit integer types                                                                  |
| `int32`, `uint32` | `i4`, `u4`   | Signed and unsigned 32-bit integer types                                                                  |
| `int64`, `uint64` | `i8`, `u8`   | Signed and unsigned 64-bit integer types                                                                  |
| `float16`         | `f2`         | Half-precision floating point                                                                             |
| `float32`         | `f4` or `f`  | Standard single-precision floating point; compatible with C `float`                                       |
| `float64`         | `f8` or `d`  | Standard double-precision floating point; compatible with C `double` and Python `float` object            |
| `float128`        | `f16` or `g` | Extended-precision floating point                                                                         |
| `complex64`       | `c8`         | Complex numbers represented by two 32-bit floats                                                           |
| `complex128`      | `c16`        | Complex numbers represented by two 64-bit floats                                                           |
| `complex256`      | `c32`        | Complex numbers represented by two 128-bit floats                                                          |
| `bool`            | `?`          | Boolean type storing `True` and `False` values                                                             |
| `object`          | `O`          | Python object type; a value can be any Python object                                                       |
| `string_`            | `S`          | Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use 'S10'                                                          |
| `unicode_`          | `U`          | Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')    


In [32]:
# mapping a dataype on a whole array
arr2 = np.array([1.23, 2.34, 3.45], dtype=np.float64)
arr2.dtype

dtype('float64')

In [33]:
strarr2 = arr2.astype(np.int16)
strarr2

array([1, 2, 3], dtype=int16)

In [34]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64) 
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])