# **Linear Algebra**

In [1]:
import numpy as np

In [7]:
x = np.array([
    [1., 2., 3.],
    [4., 5., 6.],
    ])

y = np.array([
    [6., 23],
    [-1 , 7],
    [8 , 9]
])

# x.dot(y)
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

A matrix product between a two-dimensional array and a suitably sized one dimensional array results in a one-dimensional array :

In [15]:
x @ np.ones(x.shape[1])

array([ 6., 15.])

numpy.linalg has a standard set of matrix decompositions and things like `inverse` and `determinant` :


In [16]:
from numpy.linalg import inv , qr

In [21]:
X = np.random.standard_normal(size=(5,5))
print(X)
inv(X)

[[ 0.55293493 -0.1688862   0.50756561 -0.27709545 -0.18784165]
 [ 1.55198589 -0.21478852  0.40166591 -0.09711739 -0.19002139]
 [ 0.42280737 -0.5088147  -0.72729585  0.53818844  1.79783431]
 [-2.24065059  1.09550524  0.19178916 -1.64068032 -0.48989603]
 [ 0.74531347 -0.35204681  0.06778463  1.10982415  0.9691348 ]]


array([[-0.83860931,  1.07750558,  0.04141717,  0.11006048,  0.02753004],
       [-2.89551597,  2.08855192, -0.47018057,  1.06153257,  1.25711964],
       [ 1.6455003 , -0.51502016, -0.33398692,  0.31845267,  0.9985097 ],
       [-0.66846308, -0.19305772, -0.54100877, -0.14740537,  0.76169025],
       [ 0.24352287,  0.18713517,  0.44025809,  0.44749962,  0.525232  ]])