In [2]:
import numpy as np

In [2]:
my_arr = np.arange(1_000_000)
my_list = list(range(1_000_00))

* NumPy-based algorithms are generally 10 to 100 times faster (or more) than their pure Python counterparts and use significantly less memory.


In [9]:
%timeit my_arr2 = my_arr * 2

1.24 ms ± 29.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
%timeit my_list2 = [x * 2 for x in my_list]

3.47 ms ± 92.6 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Arrays enable you to
perform mathematical operations on whole blocks of data using similar syntax to the
equivalent operations between scalar elements.

In [11]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
data * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [16]:
data + data

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [22]:
data.ndim

2

In [20]:
data.shape

(3, 3)

In [21]:
data.dtype

dtype('int32')

converting lists into arrays :

In [24]:
lst1 = [[1,1,1,1],[1,1,1,1]]
arr1 = np.array(lst1)
arr1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
np.zeros([4,6])

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

### important NumPy array creation functions
| Function         | Description                                                                                                                                          |
|------------------|------------------------------------------------------------------------------------------------------------------------------------------------------|
| `array`          | Convert input data (list, tuple, array, or other sequence type) to an ndarray either by inferring a data type or explicitly specifying a data type; copies the input data by default. |
| `asarray`        | Convert input to ndarray, but do not copy if the input is already an ndarray.                                                                        |
| `arange`         | Like the built-in `range` but returns an ndarray instead of a list.                                                                                  |
| `ones`           | Produce an array of all 1s with the given shape and data type.                                                                                       |
| `ones_like`      | Takes another array and produces a ones array of the same shape and data type.                                                                       |
| `zeros`          | Like `ones` but producing arrays of 0s instead.                                                                                                      |
| `zeros_like`     | Takes another array and produces a zeros array of the same shape and data type.                                                                      |
| `empty`          | Create new arrays by allocating new memory, but do not populate with any values like `ones` and `zeros`.                                             |
| `empty_like`     | Takes another array and produces an empty array of the same shape and data type.                                                                     |
| `full`           | Produce an array of the given shape and data type with all values set to the indicated “fill value.”                                                 |
| `full_like`      | Takes another array and produces a filled array of the same shape and data type.                                                                     |
| `eye`, `identity`| Create a square N × N identity matrix (1s on the diagonal and 0s elsewhere).                                                                         |


### Numpy Datatypes :
| Type          | Type Code  | Description                                                                                               |
|---------------|------------|-----------------------------------------------------------------------------------------------------------|
| `int8`, `uint8`   | `i1`, `u1`   | Signed and unsigned 8-bit (1 byte) integer types                                                          |
| `int16`, `uint16` | `i2`, `u2`   | Signed and unsigned 16-bit integer types                                                                  |
| `int32`, `uint32` | `i4`, `u4`   | Signed and unsigned 32-bit integer types                                                                  |
| `int64`, `uint64` | `i8`, `u8`   | Signed and unsigned 64-bit integer types                                                                  |
| `float16`         | `f2`         | Half-precision floating point                                                                             |
| `float32`         | `f4` or `f`  | Standard single-precision floating point; compatible with C `float`                                       |
| `float64`         | `f8` or `d`  | Standard double-precision floating point; compatible with C `double` and Python `float` object            |
| `float128`        | `f16` or `g` | Extended-precision floating point                                                                         |
| `complex64`       | `c8`         | Complex numbers represented by two 32-bit floats                                                           |
| `complex128`      | `c16`        | Complex numbers represented by two 64-bit floats                                                           |
| `complex256`      | `c32`        | Complex numbers represented by two 128-bit floats                                                          |
| `bool`            | `?`          | Boolean type storing `True` and `False` values                                                             |
| `object`          | `O`          | Python object type; a value can be any Python object                                                       |
| `string_`            | `S`          | Fixed-length ASCII string type (1 byte per character); for example, to create a string data type with length 10, use 'S10'                                                          |
| `unicode_`          | `U`          | Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')    


In [32]:
# mapping a dataype on a whole array
arr2 = np.array([1.23, 2.34, 3.45], dtype=np.float64)
arr2.dtype

dtype('float64')

In [33]:
strarr2 = arr2.astype(np.int16)
strarr2

array([1, 2, 3], dtype=int16)

In [34]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64) 
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

Comparisons between arrays of the same size yield Boolean arrays:

In [35]:
arr1 = np.array([[1,0,1],
                 [0,1,0],])
arr2 = np.array([[1,1,1],
                 [0,0,0]])
arr1 > arr2

array([[False, False, False],
       [False,  True, False]])

## array slicing :

In [47]:
arr2d = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
arr2d[::-1,0]

array([10,  7,  4,  1])

In [63]:
arr3d = np.array([
    [[1, 2, 3],
      [4, 5, 6]], 
    [[7, 8, 9],
      [10, 11, 12]]])

arr2d_temp = arr3d[0].copy()
arr2d_temp

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
arr3d[0] = 0
arr3d

array([[[ 0,  0,  0],
        [ 0,  0,  0]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# **Indexing**
## -Boolean Indexing

In [107]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],[-12, -4], [3, 4]])
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [74]:
data[names == "Bob"]

array([[4, 7],
       [0, 0]])

The Boolean array must be of the same length as the array axis it’s indexing. You can even mix and match Boolean arrays with slices

In [78]:
data[names == "Bob", :1 ]

array([[4],
       [0]])

In [84]:
data[~(names == "Bob")]
# data[names != "Bob"]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [102]:
condition = names == "Joe"
data[condition]


array([[  0,   2],
       [-12,  -4],
       [  3,   4]])

* combine multiple Boolean conditions, use Boolean arithmetic operators like & (and) and | (or):

In [103]:
mask = (names == "Will") | condition
data[mask , ::]

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [114]:
# converting every negative number to 0
data_copy = data.copy()
filter = data < 0
data_copy[filter] = 0
data_copy

array([[4, 7],
       [0, 2],
       [0, 6],
       [0, 0],
       [1, 2],
       [0, 0],
       [3, 4]])

You can also set whole rows or columns using a one-dimensional Boolean array:


In [115]:
data_copy[names!="Joe"] = 1
data_copy

array([[1, 1],
       [0, 2],
       [1, 1],
       [1, 1],
       [1, 1],
       [0, 0],
       [3, 4]])

## - Indexing :

In [8]:
arr = np.zeros((8,4))
for i in range(arr.shape[0]):
    arr[i] = i
arr[[4,3]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.]])

In [17]:
arr = np.arange(32).reshape((8,4))
print(arr)
arr[[1, 5, 7, 2], [0, 3, 1, 2]]
# Here the elements (1, 0), (5, 3), (7, 1), and (2, 2) were selected.

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([ 4, 23, 29, 10])

transposing an array :

In [22]:
arr = np.arange(15).reshape((3,5))
print(arr)
arr.T

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [23]:
arr = np.arange(15).reshape((3,5))
print(arr)
arr.swapaxes(0,1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### numpy.random

In [18]:
samples = np.random.standard_normal(size=(5, 4))
samples

array([[ 0.48292545, -1.7362673 , -1.71988605, -0.02695273],
       [ 0.72319473,  0.38130838, -0.16190923, -0.05061843],
       [ 1.20837175, -0.51880655, -0.17463807, -1.35563415],
       [ 0.48250143, -0.62721492, -1.94990684,  0.93255682],
       [-0.48240112, -1.58947433, -0.58787877,  0.94205792]])